project:
  type: website
  output-dir: docs

website:
  title: "Disease modeling for public health"
  site-url: https://www.jonghoonk.com
  description: "Disease modeling for public health"
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Publications
        href: research/index.qmd
      - icon: graph-up
        href: https://www.jonghoonk.com/dashboard_stock
      - icon: github
        href: https://github.com/kimfinale
      - icon: linkedin
        href: https://www.linkedin.com/in/jong-hoon-kim-6447325/
      - icon: twitter
        href: https://twitter.com/tarzanthoreau
format:
  html:
    theme:
      - cosmo
      - html/mytheme.scss


editor: source


